In [2]:
import pandas as pd
import os

In [4]:
folder_path = "C:/Users/aatif/Downloads/ml part in project/LUAD_TUMOR_RAW"

for file in os.listdir(folder_path):
    if file.endswith(".tsv"):
        file_path = os.path.join(folder_path, file)
        
        df = pd.read_csv(file_path, sep="\t", comment="#")
        
        df = df[["gene_name", "tpm_unstranded"]]
        
        df = df[df["gene_name"].notna()]
        df = df[~df["gene_name"].str.startswith("N_")]
        
        print(file, df.head())
        break  # just testing one file

02f6c9d4-8296-4e00-9e78-4f4d8c942340.rna_seq.augmented_star_gene_counts.tsv   gene_name  tpm_unstranded
4    TSPAN6         30.4171
5      TNMD          0.0909
6      DPM1        110.8626
7     SCYL3          4.2119
8  C1orf112          6.7894

In [6]:
genes = ["FAS", "FADD", "TNFRSF10B", "CASP8", "CASP10", "BAX",	"BAK1", "BCL2", "BCL2L1", "BID", "BAD", "CYCS", "APAF1", "CASP9", "CASP3", "CASP6", "CASP7", "XIAP", "DIABLO", "TP53", "MDM2", "ATM", "ATR", "CDKN1A", "AKT1", "PIK3CA","MAPK1", "MAPK3",	"NFKB1", "RELA",] 


folder_path = "C:/Users/aatif/Downloads/ml part in project/LUAD_TUMOR_RAW"

data_list = []

for file in os.listdir(folder_path):
    if file.endswith(".tsv"):
        file_path = os.path.join(folder_path, file)
        
        df = pd.read_csv(file_path, sep="\t", comment="#")
        
        # Keep only needed columns
        df = df[["gene_name", "tpm_unstranded"]]
        
        # Clean unwanted rows
        df = df[df["gene_name"].notna()]
        df = df[~df["gene_name"].str.startswith("N_")]
        
        # Keep only your genes
        df = df[df["gene_name"].isin(genes)]
        
        # Convert to dictionary
        gene_dict = dict(zip(df["gene_name"], df["tpm_unstranded"]))
        
        # Create row (ensure all genes exist)
        row = [gene_dict.get(gene, 0) for gene in genes]
        
        # Add label (1 = tumor)
        row.append(1)
        
        data_list.append(row)

# Create DataFrame
columns = genes + ["Label"]
tumor_df = pd.DataFrame(data_list, columns=columns)

In [9]:
tumor_df.shape

(100, 31)

In [12]:
tumor_df.head()

,FAS,FADD,TNFRSF10B,CASP8,CASP10,BAX,BAK1,BCL2,BCL2L1,BID,...,ATM,ATR,CDKN1A,AKT1,PIK3CA,MAPK1,MAPK3,NFKB1,RELA,Label
0,11.6697,13.3585,158.4044,26.5722,11.9679,75.1224,35.4951,4.3844,73.7104,38.2904,...,12.5972,6.2538,136.2297,27.3670,13.4222,81.0409,44.1161,73.2382,105.7926,1
1,19.0507,3.5578,48.7033,23.9646,18.0045,33.0659,58.9582,10.1491,112.4884,13.4838,...,10.1563,3.9362,161.5080,23.7168,8.9378,101.3706,71.9187,84.5959,84.0289,1
2,15.5036,3.6328,64.4398,23.6920,26.4979,88.4429,52.9748,6.0523,243.2411,28.5586,...,9.1624,6.3366,204.2766,59.4045,4.5761,55.3551,66.8001,39.8126,50.7216,1
3,4.6707,4.4613,61.0191,14.0984,17.0449,41.4829,34.2208,1.0745,54.6836,5.2957,...,4.0727,2.5382,47.2420,33.8426,5.6699,115.8968,82.4880,20.2200,50.0994,1
4,21.0430,3.1816,54.7599,15.8484,24.0508,87.1233,53.6022,3.9066,144.3732,55.3837,...,8.1841,6.6455,61.3066,63.6607,10.0352,151.1742,68.7230,43.3466,81.6458,1

In [14]:
tumor_df.to_csv("tumor_data.csv", index=False)

In [25]:
normal_path = "C:/Users/aatif/Downloads/ml part in project/LUAD_NORMAL_RAW"

data_list = []   # VERY IMPORTANT (reset here)

for file in os.listdir(normal_path):
    if file.endswith(".tsv"):
        file_path = os.path.join(normal_path, file)
        
        df = pd.read_csv(file_path, sep="\t", comment="#")
        
        # Keep required columns
        df = df[["gene_name", "tpm_unstranded"]]
        
        # Clean unwanted rows
        df = df[df["gene_name"].notna()]
        df = df[~df["gene_name"].str.startswith("N_")]
        
        # Keep only selected genes
        df = df[df["gene_name"].isin(genes)]
        
        # Convert to dictionary
        gene_dict = dict(zip(df["gene_name"], df["tpm_unstranded"]))
        
        # Create row (ensure all genes present)
        row = [gene_dict.get(gene, 0) for gene in genes]
        
        # Add label (0 = normal)
        row.append(0)
        
        data_list.append(row)

# Create DataFrame
columns = genes + ["Label"]
normal_df = pd.DataFrame(data_list, columns=columns)

In [26]:
print(normal_df.shape)

(57, 31)

In [27]:
print(normal_df["Label"].value_counts())

Label
0    57
Name: count, dtype: int64

In [29]:
normal_df.head()

,FAS,FADD,TNFRSF10B,CASP8,CASP10,BAX,BAK1,BCL2,BCL2L1,BID,...,ATM,ATR,CDKN1A,AKT1,PIK3CA,MAPK1,MAPK3,NFKB1,RELA,Label
0,17.5559,3.8579,32.1320,9.7833,11.8075,58.4260,22.3645,3.5367,126.0830,27.1094,...,2.8964,1.0162,189.1789,29.2169,4.1224,70.6613,86.3983,32.8719,47.8549,0
1,22.5554,2.9369,46.3826,16.6030,21.2457,46.1177,19.2454,5.4931,95.8430,17.2384,...,9.1318,3.0666,218.7492,40.3860,9.4569,120.3703,110.5224,46.1797,72.5189,0
2,12.3326,3.6042,56.3467,17.8350,18.9345,47.5541,17.8466,3.4710,60.5564,15.2762,...,8.5199,3.3045,128.5683,40.4357,6.9353,93.1601,62.3999,42.9796,53.7886,0
3,29.2263,1.3299,59.2901,14.6675,23.8553,50.6566,22.3549,6.8302,75.2715,13.1246,...,9.1440,3.1374,463.7148,28.7097,9.5656,91.5650,73.9120,77.0753,67.9849,0
4,18.8490,2.0572,57.1314,15.4863,16.9528,80.9696,27.7980,5.4112,91.4463,17.4582,...,7.2261,2.6151,302.2627,36.1401,6.3211,78.7356,56.9072,42.8651,49.0656,0

In [31]:
normal_df.to_csv("normal_data_clean.csv", index=False)

In [33]:
tumor_df = pd.read_csv("tumor_data.csv")
normal_df = pd.read_csv("normal_data_clean.csv")

final_df = pd.concat([tumor_df, normal_df], ignore_index=True)

In [35]:
final_df["Label"].value_counts()

Label
1    100
0     57
Name: count, dtype: int64

In [37]:
final_df = final_df.sample(frac=1, random_state=42).reset_index(drop=True)

In [39]:
final_df.to_csv("final_dataset_clean.csv", index=False)